export const metadata = {
    title: 'Truyện tranh',
    description: 'Generated by create next app',
    other: {
        referrer: "same-origin"
    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,

}) {
    return (
        <div className="">
            {children}
        </div>
    )
}
