import { Metadata, ResolvingMetadata } from 'next'
import { ExtendManga } from '../../../../api/extend'
import { getMangaTitle } from '../../../../utils/getMangaTitle'
import transLocalizedStr from '../../../../utils/transLocalizedStr'

// export const metadata: Metadata = {
//     title: 'Truyện tranh',
//     description: 'Generated by create next app',
//     other: {
//         referrer: "same-origin"
//     }
// }

type Props = {
    params: { mangaId: string }
    searchParams: { [key: string]: string | string[] | undefined }
}

export async function generateMetadata(
    { params, searchParams }: Props,
    parent: ResolvingMetadata
): Promise<Metadata> {
    // read route params
    const id = params.mangaId

    const previousImages = (await parent).openGraph?.images || []
    try {
        // fetch data
        const { data: manga }: { data: ExtendManga } = await fetch(`https://api.mangadex.org/manga/${id}`).then((res) => res.json())
        return {
            title: `${getMangaTitle(manga)} - Đọc ngay tại NetTrom`,
            description: transLocalizedStr(manga.attributes.description),
            openGraph: {
                images: [`https://og.mangadex.org/og-image/manga/${id}`, ...previousImages],
            },
        }
    } catch (error) {

    }
    // optionally access and extend (rather than replace) parent metadata

    return {
        title: "Đọc ngay tại NetTrom",
        description: "NetTrom - Website Trộm Truyện Văn Minh",
        openGraph: {
            images: [`https://og.mangadex.org/og-image/manga/${id}`, ...previousImages],
        },
    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,

}) {
    return (
        <div className="">
            {children}
        </div>
    )
}
