# Generated by Django 5.1.2 on 2024-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sfw', models.IntegerField()),
                ('genres', models.CharField(max_length=100)),
                ('themes', models.CharField(max_length=100)),
                ('demographics', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=1000)),
                ('background', models.CharField(max_length=1000)),
                ('title_english', models.CharField(max_length=100)),
                ('title_japanese', models.CharField(max_length=100)),
                ('title_synonyms', models.CharField(max_length=100)),
            ],
        ),
    ]
